[build]
builder = "NIXPACKS"

[build.nixpacks]
packages = ["nodejs", "npm"]

[build.env]
NODE_ENV = "production"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10