name: Design Review (Playwright)

on:
  pull_request:
    branches: [ main ]

jobs:
  design-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          npx playwright install --with-deps chromium

      - name: Start web app
        run: |
          docker compose up -d
          echo "Waiting for app..." && sleep 10

      - name: Run Playwright tests (basic + a11y)
        working-directory: frontend
        env:
          BASE_URL: http://localhost:3000
        run: npx playwright test --reporter=html

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report


